name: S
author: firsttry
main: io.github.randomkiddo.s.Main
version: 1.4.1
commands:
  s:
    usage: /s
    description: Auto-creative and vanish
    permission: s.op
    permission-message: You don't have enough credentials to run this command!